import Head from "next/head";
import { Inter } from "@next/font/google";
import { GetStaticProps, NextPage } from "next";
import { Character, GetCharacterResults } from "../types";
import Image from "next/image";
import imageLoader from "../imageLoader";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const getStaticProps: GetStaticProps = async (context) => {
	// fetch the dummy API
	const resp = await fetch("http://rickandmortyapi.com/api/character");
	const { results }: GetCharacterResults = await resp.json();

	return {
		props: { characters: results },
	};
};

const Home: NextPage<{ characters: Character[] }> = ({ characters }) => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			DB CONNECTION: {process.env.NEXT_PUBLIC_DB_CONNECT}
			<div>
				<div>
					{characters.map((character) => (
						<div key={character.id}>
							<Image
								loader={imageLoader}
								unoptimized
								src={character.image}
								alt={character.image}
								width={200}
								height={200}
							/>
							<Link href={`characters/${character.id}`}>
								<h3>{character.name}</h3>
							</Link>
						</div>
					))}
				</div>
			</div>
		</>
	);
};

export default Home;
